name: molssi_best_practices
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python==3.11
  - pip

    # Package depends
  - numpy
  - matplotlib
  - black 
  - pytest-cov
  - pytest
  - sphinx-autoapi
  - coverage
  - flake8
  - ipython
  - sphinx
  - sphinx-autoapi
  - sphinx-rtd-theme
